### ISSUE TITLE
Almost all doc pages lead to a 404 and the left-side navigation is missing

### ISSUE THREAD

**Issue by bttger** [canonical-web-and-design/microk8s.io#397]
## Summary

The title says it all. Just wanted to look up the command reference but it appears that almost all doc pages lead to a 404.

Also, the left-side navigation is missing.

## Process

Go to the microk8s docs: https://microk8s.io/docs

Scroll down to the links. Click on any of the links.

## Browser details

Checked on Chrome (Version 89.0.4389.114 (Official Build) (64-bit)) and Firefox (87.0 (64 Bit)).

**Comment by evilnick** [comment]
Thanks for reporting this - we are already aware of the issue and are working to fix it. In the meantime, you can access the content of the docs from the kubernetes discourse - https://discuss.kubernetes.io/t/introduction-to-microk8s/11243

**Comment by evilnick** [comment]
Fixed now ;)

**Comment by bttger** [comment]
@evilnick  It's not fixed for me. Still the same issue, though the left-side navigation menu is available again. But the links still lead to a 404.

**Comment by evilnick** [comment]
yes, sorry about that. We seem to have fixed the navigation issue but not the 404 one. We are still trying to work out what exactly is causing that

**Comment by bttger** [comment]
No problem, thanks for the discourse link :)

**Comment by anthonydillon** [comment]
Thanks for taking the time to report this issue to us. This issue has been resolved.
